name: tc-cloudgames-foundation
resource-group: ${env:resourceGroup}   # definido pelo env.json
location: ${env:location}

services:

  # 1️⃣ Container App Environment
  containerAppEnv:
    type: containerAppEnvironment
    properties:
      logAnalyticsWorkspaceId: ${env:logAnalyticsWorkspaceId}

  # 2️⃣ Key Vault
  keyVault:
    type: keyVault
    properties:
      name: tccloudgamesdevwox7kv      # nome fixo
      sku: standard
      enableSoftDelete: true
      enablePurgeProtection: false
      accessPolicies: []                # MI do ACA Environment será configurada automaticamente
      tags: ${env:tags}

tags: ${env:tags}
