name: tc-cloudgames-foundation
metadata:
  template: tc-cloudgames-foundation@0.0.1

# Use existing resource group and location from Terraform
resourceGroup: ${AZURE_RESOURCE_GROUP}
location: ${AZURE_LOCATION}

# No infrastructure - all created by Terraform
# AZD is just an orchestrator for future Container Apps

# Hooks for validation and information
hooks:
  predeploy:
    shell: sh
    run: |
      echo "🔍 TC CloudGames Foundation - AZD Orchestrator"
      echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      echo "📋 Terraform Foundation Resources (Already Created):"
      echo "   • Resource Group: ${AZURE_RESOURCE_GROUP}"
      echo "   • Location: ${AZURE_LOCATION}"
      echo "   • Log Analytics: ${LOG_ANALYTICS_WORKSPACE_ID}"
      echo "   • Container App Environment: Ready for apps"
      echo "   • Key Vault: Empty, ready for secrets"
      echo "   • PostgreSQL, Redis, ACR, Service Bus: Ready"
      echo ""
      echo "🚀 Next Steps:"
      echo "   • Users API: Deploy with dedicated AZD"
      echo "   • Games API: Deploy with dedicated AZD" 
      echo "   • Payments API: Deploy with dedicated AZD"
      echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      
  postdeploy:
    shell: sh
    run: |
      echo "✅ Foundation orchestration complete!"
      echo "🔗 All infrastructure ready for microservices deployment."
